name: Test
on:
  pull_request:                        # プルリクエストが作成されたら起動
    paths: ['go/**/*.go']              # ただしGoのファイル変更時のみテスト対象にする
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4      # ステップ1: チェックアウト これでソースコードへのアクセスを許可してる
      - uses: actions/setup-go@v5      # ステップ2: 言語セットアップ
        with:
          go-version: '1.22'
      - run: go test go/excellent/*.go # ステップ3: テストの実行